### ISSUE TITLE
Minor Issue: VS Code IDE Reports `import.meta` Module Option Problem

### ISSUE THREAD

**Issue by alexb7217** [Uninen/vite-ts-tailwind-starter#200]
This is probably a temporary and minor issue, posting just in case it might help another VS Code user until the vite version is updated here.

Found a discussion and solution on the vite GH repo here: https://github.com/vitejs/vite/issues/6311
Using import.meta.url in vite.config.ts shows error in IDE (VS Code) #6311 

The problem message shown, on clean install of vite-ts-tailwind-starter:

> The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node12', or 'nodenext'. ts(1343)

I was able to make the problem message go away by updating vite to an incremental version

In package.json - update vite to fixed version:
```
"vite": "~2.7.13",
```

**Comment by Uninen** [comment]
Yup, doesn't seem to be a problem with the template but Vite itself. Just pushed a new version that fixes this.

Thanks for the report, feel free to reopen this if something doesn't work 👍
