### ISSUE TITLE
First attempt to run dev: ECONNREFUSED error connecting to TCP host:localhost port:3000 

### ISSUE THREAD

**Issue by KenEucker** [Uninen/vite-ts-tailwind-starter#202]
After successfully installing dependencies, I am setting this error on first run of `yarn dev`:

`making TCP connection to 3000 ...
  error connecting to TCP host:localhost port:3000 Error: connect ECONNREFUSED ::1:3000`

![Screen Shot 2022-01-25 at 12 00 55 PM](https://user-images.githubusercontent.com/1720267/151050727-a744ada3-7c55-4858-8218-b91476b7f012.png)

Is there a step I missed to getting this project up and running?

**Comment by KenEucker** [comment]
Welp. Nevermind me.

**Comment by zacharyplotkin** [comment]
Hey, how did you fix this? Sorry if it's something super trivial, I'm trying to dockerize the client, and I'm running into some trouble (the same error you are running into)
