### ISSUE TITLE
Its better to separate vitest config from vite config file

### ISSUE THREAD

**Issue by YusufcanY** [Uninen/vite-ts-tailwind-starter#211]
I didn't change anything in boilerplate and in `vite.config.ts` file its giving these error:
```
Argument of type '{ plugins: any[]; resolve: { alias: { '@': string; }; }; test: { include: string[]; }; }' is not assignable to parameter of type 'UserConfigExport'.
  Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.ts(2345)
Argument of type '{ plugins: any[]; resolve: { alias: { '@': string; }; }; test: { include: string[]; }; }' is not assignable to parameter of type 'UserConfigExport'.
  Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.ts(2345)
```
When create a new file named `vitest.config.ts` and move test object to that file its works fine. Here is my `vitest.config.ts`:
```
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/unit/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
  },
});
```

**Comment by Uninen** [comment]
Thanks for the input! The [type reference](https://github.com/Uninen/vite-ts-tailwind-starter/blob/main/vite.config.ts#L1) is documented way to configure Vitest, but you're right that current versions also support `vitest.config.ts` which is more explicit way to configure it so we should be using that instead.

If you want to contribute a PR I'm happy to merge it 👍
