### ISSUE TITLE
playwright breaking changes

### ISSUE THREAD

**Issue by WebPirat** [Uninen/vite-ts-tailwind-starter#223]
Hi 

playwright changed the cfg for ct testing
https://playwright.dev/docs/release-notes#%EF%B8%8F-breaking-change-in-component-tests

after that i get 

` Rollup failed to resolve import "@vue/compiler-dom" from "D:/Git/onboarding-frontend/playwright/index.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
`

**Comment by Uninen** [comment]
Thanks for reporting the issue. Playwright is not the best tool to use for Vue component testing atm, using Vitest for that is faster and more robust. I'll change the template to use Vitest for component tests and Playwright just for the e2e testing.

**Comment by WebPirat** [comment]
Thanks other that problem this template looks awesome thanks for sharing!

**Comment by Uninen** [comment]
Thanks again for the report @WebPirat, I refactored this now and also added coverage reporting to PR comments ([live example here](https://github.com/Uninen/vite-ts-tailwind-starter/pull/225#issuecomment-1507477206)), Vitest works great for component testing 👍
